apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: dns-management
    app.kubernetes.io/part-of: platform-infrastructure
    azure.workload.identity/use: "true"
    platform.io/layer: infrastructure
    platform.io/managed-by: platform-team
  annotations:
    platform.io/component: external-dns
    platform.io/description: "Namespace for External DNS automated DNS record management"
