apiVersion: v1
kind: Namespace
metadata:
  name: azureserviceoperator-system
  labels:
    name: azureserviceoperator-system
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    azure.workload.identity/use: "true"
