apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

labels:
- pairs:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: certificate-management
    managed-by: flux

# # Replace client ID from identity ConfigMap
# replacements:
#   - source:
#       kind: ConfigMap
#       name: cert-manager-identity-eso
#       namespace: flux-system
#       fieldPath: data.clientId
#     targets:
#       - select:
#           group: helm.toolkit.fluxcd.io
#           kind: HelmRelease
#           name: cert-manager
#         fieldPaths:
#           - spec.values.serviceAccount.annotations.[azure.workload.identity/client-id]
#           - spec.values.webhook.serviceAccount.annotations.[azure.workload.identity/client-id]
#           - spec.values.cainjector.serviceAccount.annotations.[azure.workload.identity/client-id]
#           - spec.values.startupapicheck.serviceAccount.annotations.[azure.workload.identity/client-id]
