apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kro
  namespace: kro
spec:
  interval: 10m
  chart:
    spec:
      chart: kro
      version: "0.4.1"
      sourceRef:
        kind: HelmRepository
        name: kro-oci
        namespace: kro
  values:
    # KRO controller configuration
    controller:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    
    # Service Account configuration
    serviceAccount:
      create: true
      name: kro-controller-manager
    
    # RBAC configuration
    rbac:
      create: true
    
    # Webhook configuration
    webhook:
      enabled: true
      port: 9443