apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kro

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

labels:
- pairs:
    app.kubernetes.io/name: kro
    app.kubernetes.io/component: controller
    platform.io/managed: "true"