apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer-staging.yaml
  - clusterissuer-production.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: certificate-management
      managed-by: flux
