apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

labels:
- pairs:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/component: workflows
    platform.io/managed: "true"