apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idp-wildcard-tls-cert
  namespace: idp-platform
  labels:
    app.kubernetes.io/name: idp-wildcard-tls-cert
    app.kubernetes.io/component: tls-certificate
    app.kubernetes.io/part-of: idp-platform
spec:
  secretName: idp-wildcard-tls-cert
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - "idp.davidmarkgardiner.co.uk"
  - "*.idp.davidmarkgardiner.co.uk"
  usages:
  - digital signature
  - key encipherment
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
---
# Certificate for aks-istio-ingress namespace (required for Istio Gateway)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idp-wildcard-tls-cert
  namespace: aks-istio-ingress
  labels:
    app.kubernetes.io/name: idp-wildcard-tls-cert
    app.kubernetes.io/component: tls-certificate
    app.kubernetes.io/part-of: idp-platform
spec:
  secretName: idp-wildcard-tls-cert
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - "idp.davidmarkgardiner.co.uk"
  - "*.idp.davidmarkgardiner.co.uk"
  usages:
  - digital signature
  - key encipherment
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days