apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aksclusters.kro.run
spec:
  group: kro.run
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterName:
                type: string
              location:
                type: string
              nodePoolType:
                type: string
              enableNAP:
                type: boolean
              dryRun:
                type: boolean
              advancedConfig:
                type: object
                properties:
                  kubernetesVersion:
                    type: string
                  maxNodes:
                    type: integer
                  enableSpot:
                    type: boolean
          status:
            type: object
            properties:
              phase:
                type: string
              message:
                type: string
              resourcesCreated:
                type: array
                items:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
  scope: Namespaced
  names:
    plural: aksclusters
    singular: akscluster
    kind: AKSCluster
    shortNames:
    - aks