apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: ${NAMESPACE_NAME}
  labels:
    app.kubernetes.io/managed-by: "idp-platform"
    idp-platform/component: "resource-limits"
  annotations:
    idp-platform/created-at: "${CREATED_AT}"
spec:
  limits:
  # Container limits
  - type: Container
    default:
      cpu: "${CPU_LIMIT}"
      memory: "${MEMORY_LIMIT}"
    defaultRequest:
      cpu: "${CPU_REQUEST}"
      memory: "${MEMORY_REQUEST}"
    max:
      cpu: "${CPU_MAX_LIMIT}"
      memory: "${MEMORY_MAX_LIMIT}"
    min:
      cpu: "10m"
      memory: "64Mi"
  # Pod limits
  - type: Pod
    max:
      cpu: "${CPU_MAX_LIMIT}"
      memory: "${MEMORY_MAX_LIMIT}"
    min:
      cpu: "10m"
      memory: "64Mi"
  # Persistent Volume Claim limits
  - type: PersistentVolumeClaim
    max:
      storage: "10Gi"
    min:
      storage: "1Gi"